#!/usr/bin/env bash
# Wave 1 Phase 1 QA — 156 sites, 4 parallel workers
# Generated 2026-03-31
set -euo pipefail

PARALLEL="${PARALLEL:-4}"
TIMEOUT="${TIMEOUT:-30000}"
CONCURRENCY="${CONCURRENCY:-4}"
OUTPUT_BASE="scans/wave1"
mkdir -p "$OUTPUT_BASE"

run_site() {
  local original="$1"
  local migrated="$2"
  local dir_name="${original#www.}"
  local dir_name="${dir_name#trust.}"
  local out_dir="$OUTPUT_BASE/$dir_name"
  local log="$OUTPUT_BASE/logs/${dir_name}.log"
  mkdir -p "$OUTPUT_BASE/logs"

  echo "[$(date +%H:%M:%S)] ▶ $original" | tee -a "$OUTPUT_BASE/batch-summary.log"

  if node dist/index.js compare-sites \
      --original "https://$original" \
      --migrated "$migrated" \
      --concurrency "$CONCURRENCY" \
      --timeout "$TIMEOUT" \
      --csv \
      --output "$out_dir" > "$log" 2>&1; then
    local bugs
    bugs=$(grep -oP "bugs: \K[0-9]+" "$log" 2>/dev/null | tail -1 || echo "?")
    local total
    total=$(grep -oP "Total diffs: +\K[0-9]+" "$log" 2>/dev/null | tail -1 || echo "?")
    echo "[$(date +%H:%M:%S)] ✓ $original — bugs: $bugs, total diffs: $total" | tee -a "$OUTPUT_BASE/batch-summary.log"
  else
    echo "[$(date +%H:%M:%S)] ✗ $original — FAILED (see $log)" | tee -a "$OUTPUT_BASE/batch-summary.log"
  fi
}

export -f run_site
export CONCURRENCY TIMEOUT OUTPUT_BASE

echo "═══════════════════════════════════════════════"
echo "  Wave 1 Phase 1 QA — 156 sites, $PARALLEL workers"
echo "  Started: $(date)"
echo "═══════════════════════════════════════════════"
echo ""

# Write all pairs to a temp file and run with xargs
PAIRS_FILE=$(mktemp)
trap "rm -f $PAIRS_FILE" EXIT

echo "www.armourtrust.com|https://armourtrust-31030806.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.rappaportwealth.com|https://rappaportwealth-31030756.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.advins.org|https://advins-31030807.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.alpinecapitalpartners.com|https://alpinecapitalpartners-31030807.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.kaneinvestment.com|https://broadridgeprod.wixstudio.com/0kd7tbawnwo0uuirpac5" >> "$PAIRS_FILE"
echo "www.irabernstein.net|https://irabernstein-31030808.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.afgplanning.com|https://afgplanning-31030807.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.frifs.com|https://frifs-31030808.brprodaccount.com" >> "$PAIRS_FILE"
echo "trust.cnb.bank|https://trustcnb-31030809.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.prairiefs.com|https://prairiefs-31030808.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.bastienmitchell.com|https://bastienmitchell-31030809.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.goldentrianglefinancialservices.com|https://goldentrianglefinancialservices-31030808.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.kossbenefits.com|https://kossbenefits-31030808.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.jameskmccauleyinsuranceagency.com|https://jameskmccauleyinsuranceagency-31030800.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.affordablehealthandmore.com|https://affordablehealthandmore-31030807.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.mgbwealth.com|https://mgbwealth-31030808.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.capstonebeaufort.com|https://capstonebeaufort-31030804.brprodaccount.com" >> "$PAIRS_FILE"
echo "pennymorgan.pfyfn.com|https://pennymorganpfyfn-31030809.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.thempmgroupllc.com|https://thempmgroupllc-31030753.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.calderwoodfinancial.com|https://calderwoodfinancial-31030804.brprodaccount.com" >> "$PAIRS_FILE"
echo "financialwellness4life.pfyfn.com|https://financialwellness4lifepfyfn-31030809.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.ascendwealthmh.com|https://ascendwealthmh-31030806.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.cbadvisors.com|https://cbadvisors-31030804.brprodaccount.com" >> "$PAIRS_FILE"
echo "sytc-mass.pfyfn.com|https://sytc-masspfyfn-31030809.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.diballc.com|https://diballc-31030808.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.americanfundsandtrusts.com|https://americanfundsandtrusts-31030806.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.americanwealthmanagement.com|https://americanwealthmanagement-31030806.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.foundationfinancialconcepts.com|https://foundationfinancialconcepts-31030802.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.vinnybarone.com|https://vinnybarone-31030807.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.bayadvisers.com|https://bayadvisers-31030806.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.tomasablanno.com|https://tomasablanno-31030807.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.capitalfinancialmgt.com|https://capitalfinancialmgt-31030804.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.kanakfinancial.com|https://kanakfinancial-31030808.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.beaconsfieldfinancial.com|https://beaconsfieldfinancial-31030806.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.thefinancialgrouponline.com|https://thefinancialgrouponline-31030807.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.goldenfinancial.net|https://goldenfinancial-31030801.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.stanleydickinson.com|https://stanleydickinson-31030807.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.markschrader.com|https://markschrader-31030808.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.bergersontax.com|https://bergersontax-31030805.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.andrewsfinancial.net|https://andrewsfinancial-31030806.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.algorithmway.com|https://algorithmway-31030807.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.americanbrokeragegroup.com|https://americanbrokeragegroup-31030807.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.cornerstonewealthmanagement.net|https://cornerstonewealthmanagement-31030803.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.brosnanfinancial.com|https://brosnanfinancial-31030805.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.belikoveandgraves.com|https://belikoveandgraves-31030806.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.benefitsconsultinggrp.com|https://benefitsconsultinggrp-31030805.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.wemasol.com|https://wemasol-31030752.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.highlandwealth.com|https://highlandwealth-31030801.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.bensonfinancialservices.com|https://bensonfinancialservices-31030805.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.glassretirement.com|https://glassretirement-31030802.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.billipema.com|https://billipema-31030805.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.capstoneforclients.com|https://capstoneforclients-31030804.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.plantoinvest.co|https://plantoinvest-31030756.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.laradorbecker.com|https://laradorbecker-31030759.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.berkaif.com|https://berkaif-31030805.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.americanseniorfinancial.com|https://americanseniorfinancial-31030806.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.bryanedwardswealthmanagement.com|https://bryanedwardswealthmanagement-31030805.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.countsfinancial.com|https://countsfinancial-31030803.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.designbenefitsinc.com|https://designbenefitsinc-31030803.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.donleander.com|https://donleander-31030803.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.empbenguy.com|https://empbenguy-31030803.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.cornerstonelifewealth.com|https://cornerstonelifewealth-31030804.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.coordinatedplanninggroup.com|https://coordinatedplanninggroup-31030804.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.forsfinancialconsulting.com|https://forsfinancialconsulting-31030802.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.garycollier.net|https://garycollier-31030802.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.pbfsi.com|https://pbfsi-31030756.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.dencoconsultants.com|https://dencoconsultants-31030803.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.focalpointfinancialservices.com|https://focalpointfinancialservices-31030802.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.higleyfinancial.com|https://higleyfinancial-31030801.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.ficcenter.com|https://ficcenter-31030802.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.kcbaron.com|https://kcbaron-31030759.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.hfcompany.net|https://hfcompany-31030801.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.byrerwealth.com|https://byrerwealth-31030804.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.lovellwealthmanagement.com|https://lovellwealthmanagement-31030759.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.donaldcash.com|https://donaldcash-31030803.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.esquivelfinancialservices.com|https://esquivelfinancialservices-31030803.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.ldhfinancial.com|https://ldhfinancial-31030759.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.diversifiedplanners.com|https://diversifiedplanners-31030803.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.greykirwan.com|https://greykirwan-31030801.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.gardinerpwm.com|https://gardinerpwm-31030802.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.investinaris.com|https://investinaris-31030800.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.legacyvisionswm.com|https://legacyvisionswm-31030759.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.svgfinancial.com|https://svgfinancial-31030753.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.harvestfg.com|https://harvestfg-31030801.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.hodnettinsurance.com|https://hodnettinsurance-31030801.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.jerrydonut.com|https://jerrydonut-31030800.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.estateresourcegroup.com|https://estateresourcegroup-31030802.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.hahnfinancialgroup.com|https://hahnfinancialgroup-31030801.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.insightprivatewealth.com|https://insightprivatewealth-31030800.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.mdinvestmentadvisors.com|https://mdinvestmentadvisors-31030758.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.finewealthmanagement.com|https://finewealthmanagement-31030802.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.know-parallel.com|https://know-parallel-31030759.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.lynchburglegacy.com|https://lynchburglegacy-31030758.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.mainelyinsurancesolutions.com|https://mainelyinsurancesolutions-31030758.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.helgariverainsurance.com|https://helgariverainsurance-31030801.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.moneystrategies.biz|https://moneystrategies-31030758.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.ipafinancialservices.com|https://ipafinancialservices-31030800.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.kanterassociates.com|https://kanterassociates-31030800.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.fcuinc.com|https://fcuinc-31030802.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.investcapitalllc.com|https://investcapitalllc-31030800.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.myrtlebeachfinancial.com|https://myrtlebeachfinancial-31030757.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.midtownfa.com|https://midtownfa-31030758.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.myintellishield.com|https://myintellishield-31030757.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.kenadvisor.com|https://kenadvisor-31030759.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.midwestwealthsolutions.com|https://midwestwealthsolutions-31030758.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.ssgretirement.com|https://ssgretirement-31030754.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.krausefinancialgroup.com|https://krausefinancialgroup-31030759.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.myreliance.com|https://myreliance-31030757.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.oldoakfinancial.com|https://oldoakfinancial-31030757.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.rlevansco.net|https://rlevansco-31030755.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.stormsandrowdon.com|https://stormsandrowdon-31030753.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.networthmatters.com|https://networthmatters-31030757.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.mtvernonassoc.com|https://mtvernonassoc-31030757.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.mfcenter.com|https://mfcenter-31030758.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.qwstrategies.com|https://qwstrategies-31030756.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.zoellnerwholefinancial.com|https://zoellnerwholefinancial-31030751.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.nealefinancial.com|https://nealefinancial-31030757.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.romeroinsurance.com|https://romeroinsurance-31030755.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.smhci.com|https://smhci-31030754.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.pwp-llc.com|https://pwp-llc-31030756.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.sterlingbenefitsgroups.net|https://sterlingbenefitsgroups-31030754.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.pathway401k.com|https://pathway401k-31030757.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.santafewealth.com|https://santafewealth-31030755.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.ruddwisdomfinancial.com|https://ruddwisdomfinancial-31030755.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.swmallc.com|https://swmallc-31030753.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.stonebrookinvestment.com|https://stonebrookinvestment-31030753.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.westcofinancialgroup.com|https://westcofinancialgroup-31030752.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.planaheadfs.com|https://planaheadfs-31030756.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.qualitytaxmo.com|https://qualitytaxmo-31030756.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.stevefehlenberg.com|https://stevefehlenberg-31030754.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.safe2retire.com|https://safe2retire-31030755.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.rodadkins.com|https://rodadkins-31030755.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.wealthmastergroupinc.com|https://wealthmastergroupinc-31030752.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.sonnysalasagency.com|https://sonnysalasagency-31030754.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.safemoneyconsultants.org|https://safemoneyconsultants-31030755.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.theplan.net|https://theplan-31030753.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.qsifinancialplanning.com|https://qsifinancialplanning-31030756.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.trivediinsurancegroup.com|https://trivediinsurancegroup-31030752.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.sjedwardsfinancial.com|https://sjedwardsfinancial-31030754.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.smrtplanning.com|https://smrtplanning-31030754.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.woodforestinsurance.com|https://woodforestinsurance-31030751.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.tinalantypas.com|https://tinalantypas-31030753.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.rginvestmentstrategies.com|https://rginvestmentstrategies-31030755.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.virjiinvestments.com|https://virjiinvestments-31030752.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.capitalmgmtinc.com|https://capitalmgmtinc-31030804.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.tiffanyfking.com|https://tiffanyfking-31030753.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.thebutlerdavis.com|https://thebutlerdavis-31030753.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.visionfc.com|https://visionfc-31030752.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.ventouxfa.com|https://ventouxfa-31030752.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.wfswealthmanagement.com|https://wfswealthmanagement-31030752.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.worthretirement.com|https://worthretirement-31030751.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.wifsfirm.com|https://wifsfirm-31030752.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.milehighinvestments.net|https://milehighinvestments-31030758.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.montalvotax.com|https://montalvotax-31030758.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.sargentgrp.com|https://sargentgrp-31030754.brprodaccount.com" >> "$PAIRS_FILE"
echo "www.smithfinancialgrouponline.com|https://smithfinancialgrouponline-31030754.brprodaccount.com" >> "$PAIRS_FILE"

# Run PARALLEL sites at a time using xargs
cat "$PAIRS_FILE" | xargs -P "$PARALLEL" -I{} bash -c '
  IFS="|" read -r orig wix <<< "{}"
  run_site "$orig" "$wix"
'

echo ""
echo "═══════════════════════════════════════════════"
echo "  Completed: $(date)"
echo "  Summary: $OUTPUT_BASE/batch-summary.log"
echo "═══════════════════════════════════════════════"
